server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.0.143.61:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: admin
  redis:
    cluster:
      nodes:
        - 10.244.1.24:6379
        - 10.244.0.22:6379
        - 10.244.2.28:6379
        - 10.244.1.23:6379
        - 10.244.0.21:6379
        - 10.244.2.26:6379
    port: 6379
    host: 10.244.1.24
    password: password123
  kafka:
    consumer:
      bootstrap-servers: 10.244.2.12:9092,10.244.2.13:9092,10.244.2.14:9092
      group-id: msa
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 10.244.2.12:9092,10.244.2.13:9092,10.244.2.14:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
